# Generated by Django 5.1.6 on 2025-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0003_exercise_chatmessage_nutritionplan_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
