# Generated by Django 5.1.6 on 2025-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0006_passwordresetotp_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
