# Generated by Django 5.1.6 on 2025-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0007_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='repeat_days',
            field=models.CharField(blank=True, help_text='Lưu JSON các thứ trong tuần, ví dụ: ["T2", "T3", "T5"]', max_length=50, null=True),
        ),
    ]
