# Generated by Django 5.1.6 on 2025-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0008_reminder_repeat_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Bật/tắt nhắc nhở'),
        ),
    ]
