# Generated by Django 5.1.6 on 2025-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0009_reminder_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_sessions/%Y/%m/'),
        ),
    ]
