# Generated by Django 5.1.6 on 2025-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0011_exercise_is_custom_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
