# Generated by Django 5.1.6 on 2025-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0012_exercise_repetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/%Y/%m/'),
        ),
    ]
