# Generated by Django 5.1.6 on 2025-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0015_workoutexercise_workoutsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
