# Generated by Django 5.1.6 on 2025-06-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0016_alter_workoutexercise_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthjournal',
            name='workout_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qlsk.workoutsession'),
        ),
    ]
