# Generated by Django 5.1.6 on 2025-06-03 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0017_healthjournal_workout_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_exercises', to='qlsk.exercise'),
        ),
    ]
