# Generated by Django 5.1.6 on 2025-06-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0019_healthmetricshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthmetricshistory',
            name='bmi',
        ),
    ]
