# Generated by Django 5.1.6 on 2025-06-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0020_remove_healthmetricshistory_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthmetricshistory',
            name='steps',
        ),
    ]
