# Generated by Django 5.1.6 on 2025-06-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0021_remove_healthmetricshistory_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetricshistory',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
