# Generated by Django 5.1.6 on 2025-06-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0022_healthmetricshistory_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
