# Generated by Django 5.1.6 on 2025-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0023_watersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HealthProfile',
        ),
    ]
