# Generated by Django 5.1.6 on 2025-06-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0025_dietgoal_mealplan_meal_delete_nutritionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietgoal',
            name='goal_type',
            field=models.CharField(choices=[('muscle_gain', 'Tăng cơ'), ('weight_loss', 'Giảm cân'), ('maintenance', 'Duy trì sức khỏe')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Bữa sáng'), ('lunch', 'Bữa trưa'), ('dinner', 'Bữa tối'), ('snack', 'Bữa phụ')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
