# Generated by Django 5.1.6 on 2025-06-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0026_alter_dietgoal_goal_type_alter_meal_meal_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
