# Generated by Django 5.1.6 on 2025-06-04 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0027_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
