# Generated by Django 5.1.6 on 2025-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlsk', '0028_user_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notified_expert',
            field=models.BooleanField(default=False, help_text='Đã thông báo cho chuyên gia khi user liên kết'),
        ),
    ]
